apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # 👈 Este es el host usado en DATABASE_URL del backend
spec:
  selector:
    app: postgres         # 👈 Debe coincidir con las labels del pod o Deployment de PostgreSQL
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
