apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-api
  labels:
    app: bot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-api
  template:
    metadata:
      labels:
        app: bot-api
    spec:
      containers:
        - name: bot-api
          image: api-bot:1.0.0  # Cambia esto por tu imagen real
          ports:
            - containerPort: 8000
          # env:
          #   - name: TELEGRAM_TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: telegram-token
          #         key: TELEGRAM_TOKEN